[build-system]
requires = [
    "wheel",
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "pybind11>=2.6.1",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "pp*"
test-extras = "test"
test-command = "pytest {project}/tests"

[tool.cibuildwheel.linux]
before-all = [
    "apt-get update -y",
    "apt-get install -y libmpfr-dev libboost-dev",
]
repair-wheel-command = []
