[build-system]
requires = [
    "wheel",
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "pybind11>=2.7.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-extras = "test"
test-command = "pytest {project}/tests"
